name: Push_workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
   # Runs every day at midnight UTC    
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print Greetings
        run: echo "Hello, World!"
      - name: print GoodBye
        run: |
          echo "Hello, World!"
          echo "workflow executed successfully!"      